import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Box, Button, Typography } from '@mui/material'
import { PersonAdd } from '@mui/icons-material'
import EmployeeList from '../component/EmployeeList'
import EmployeeForm from '../component/EmployeeForm'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[isFormOpen,setIsFormOpen]=useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{px:3}}>
        <Typography variant='h4' align={'center'}>Employee Management</Typography>
        <Button variant='contained' onClick={()=>{setIsFormOpen(!isFormOpen)}} disableElevation color='secondary' endIcon={<PersonAdd fontSize='18px' />} sx={{textTransform:'none',fontSize:'15px'}}>Add Employee</Button>
        {
          isFormOpen && <EmployeeForm/>
        }
        <EmployeeList/>
      </Box>
     
    </>
  )
}
